Whitelist:
  - 127.0.0.1
  - 127.0.0.2
Ftp:
  Host: ftp://testgm.luckwx.com
  User: launcher
  Password: B:6t8*e<hA+&]Xte
Regions:
  -
    RegionId: 1
    WorkDir: C:\Users\Administrator\source\repos\XiuZhenServerLauncher\XiuZhenServerLauncher\bin
    Start: test.bat
    Stop: test.bat