# LauncherUrl: 127.0.0.1:9599
# Archive: servers
# 白名单，可配置多个。服务器最好在外层设置白名单
Whitelist:
  - 127.0.0.1
# 从配置的 FTP 上下载更新包
Ftp:
  Host: ftp://testgm.luckwx.com
  Port: 21
  User: launcher
  Password: y.7[.8s9NSEzq$[m
  Path: /ServerFengCe
Regions:
  -
    # 区 id，一台服务器可能会部署多个区
    RegionId: 1
    WorkDir: C:\Users\Administrator\source\repos\xx-launcher\workdir
    Start: start.bat
    Stop: stop.bat
    Bat: start.bat